apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-transformer-demo
  labels:
    app: ml-transformer-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-transformer-demo
  template:
    metadata:
      labels:
        app: ml-transformer-demo
    spec:
      containers:
      - name: api
        image: ml-transformer-demo:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: PYTHONPATH
          value: "/app"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ml-transformer-demo-service
spec:
  selector:
    app: ml-transformer-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer